const textList: string[] = [
  'Alan drops an "F bomb"',
  'Micah says "Burst"',
  "Gary mentions Barcelona",
  "Gary mentions Leicester",
  "Alan mentions Golf",
  'Micah referred to as "Big Meeks"',
  "Alan makes fun of Gary's age'",
  "Anyone mentions drinking",
  "Anyone mentions being rich",
  "Gary mentions Japan",
  "Alan mentions his goals record",
  'Micah says "RAPID"',
  'Micah says "VAR"',
  "Micah snaps his fingers",
  "Alan curses",
  "Alan's audio sounds like hes on the loo",
  'Mich says "Shambolic"',
  'Anyone says "Absolutely Ridiculous"',
  "Anyone mentions Gary's love life",
  "Micah mentions Man City",
  "Alan mentions Newcastle",
  "Alan may have had a drink",
  'Micah shouts "Hold On!',
  "Gary mentions his debut hattrick",
];

export default textList;
