const textList: string[] = [
  'Alan drops an "F bomb"',
  "Alan calls Gary's old'",
  "Alan mentions his goals record",
  "Alan's audio sounds like hes on the loo",
  "Alan mentions Newcastle",
  "Alan may have had a drink",
  'Micah says "Burst"',
  'Micah says "RAPID"',
  'Micah says "VAR"',
  "Micah snaps his fingers",
  'Micah says "Shambolic"',
  "Micah mentions Man City",
  'Micah shouts "Hold On!"',
  "Gary mentions Barcelona",
  "Gary mentions Leicester",
  "Gary mentions Japan",
  "Gary mentions his debut hattrick",
  "Gary or Micah curse",
  "Gary mentions his golden boot",
  "Anyone mentions Golf",
  "Anyone mentions drinking",
  "Anyone mentions being rich",
  'Anyone says "Absolutely Ridiculous"',
  "Anyone mentions Gary's love life",
  "Gazza",
  "Big Meeks",
  "ZABALETA",
];

export default textList;
